name: "Docker Build"
inputs:
  app-name:
    required: true
  environment:
    required: true
  docker-target:
    required: true
  docker-file:
    default: docker/Dockerfile
outputs:
  tags:
    value: ${{ steps.meta.outputs.tags }}
  digest:
    value: ${{ steps.build.outputs.digest }}
runs:
  using: "composite"
  steps:
    - id: buildx
      uses: docker/setup-buildx-action@v2
    - id: docker-cache
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ inputs.app-name }}-${{ inputs.environment }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ inputs.app-name }}-${{ inputs.environment }}-
    - id: meta
      uses: docker/metadata-action@v4
      with:
        images: "ghcr.io/crgeary/w-${{ inputs.app-name }}"
        tags: |
          type=sha,enable=true,prefix=${{ inputs.docker-target == 'migrations' && 'migrations-' || '' }},format=long
        labels: org.opencontainers.image.title=${{ inputs.app-name }}
          org.opencontainers.image.vendor=CrGeary
    - id: build
      uses: docker/build-push-action@v4
      with:
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: ${{ inputs.docker-target == 'production' && 'type=local,dest=/tmp/.buildx-cache-new' || '' }}
        target: ${{ inputs.docker-target }}
        build-args: |
          APP_NAME=${{ inputs.app-name }}
        push: true
        file: ${{ inputs.docker-file }}
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
