name: Deployment

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_ENV: production
  APP_NAME: blue

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
        id: buildx
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: "crgeary/w-${{ env.APP_NAME }}"
          tags: |
            type=sha,enable=true,prefix=migrations-,format=long
      - run: |
          echo '${{ toJson(steps.meta.outputs.tags) }}'
          echo '${{ toJson(steps.meta.outputs.labels) }}'
      # - uses: docker/build-push-action@v4
      #   id: build
      #   with:
      #     cache-from: type=local,sc=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache-ne
      #     target: production
      #     build-args: |
      #       APP_NAME=${{ env.APP_NAME }}
      #     push: true
      #     file: docker/Dockerfile
      #     context: .
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      # - run: |
      #     bash scripts/deploy.sh
