name: Deployment

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_ENV: production
  APP_NAME: blue

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      app-names: ${{ steps.calculate.outputs.app-names }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: calculate
        run: |
          echo "app-names=$(git diff --name-only ${{ github.event.before }}...${{ github.event.after }} -- apps/ | sed -E 's/apps\/([a-z0-9\-]+)\/.*$/\1/g' | awk '!seen[$0]++' | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT

  prepare:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.APP_ENV }}
      app-name: ${{ env.APP_NAME }}
    steps:
      - run: |

  build-app:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      packages: write
    outputs:
      docker_tags: ${{ steps.meta.outputs.tags }}
      docker_digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
        id: buildx
      - uses: actions/cache@v2
        id: docker-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ needs.prepare.outputs.app-name }}-${{ needs.prepare.outputs.environment }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ needs.prepare.outputs.app-name }}-${{ needs.prepare.outputs.environment }}-
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: "ghcr.io/crgeary/w-${{ env.APP_NAME }}"
          tags: |
            type=sha,enable=true,format=long
          labels: org.opencontainers.image.title=${{ env.APP_NAME }}
            org.opencontainers.image.vendor=CrGeary
      - uses: docker/build-push-action@v4
        id: build
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          target: production
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
          push: true
          file: docker/Dockerfile
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-migrations:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      packages: write
    outputs:
      docker_tags: ${{ steps.meta.outputs.tags }}
      docker_digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
        id: buildx
      - uses: actions/cache@v2
        id: docker-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ needs.prepare.outputs.app-name }}-${{ needs.prepare.outputs.environment }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ needs.prepare.outputs.app-name }}-${{ needs.prepare.outputs.environment }}-
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: "ghcr.io/crgeary/w-${{ env.APP_NAME }}"
          tags: |
            type=sha,enable=true,prefix=migrations-,format=long
          labels: org.opencontainers.image.title=${{ env.APP_NAME }}
            org.opencontainers.image.vendor=CrGeary
      - uses: docker/build-push-action@v4
        id: build
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          target: production
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
          push: true
          file: docker/Dockerfile
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  scan:
    runs-on: ubuntu-latest
    needs:
      - prepare
      - build-app
    permissions:
      security-events: write
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build-app.outputs.docker_tags }}
          format: "sarif"
          output: "trivy-${{ needs.prepare.outputs.environment }}-scan.sarif"
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-${{ needs.prepare.outputs.environment }}-scan.sarif"

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.prepare.outputs.environment }}-${{ needs.prepare.outputs.environment }}
      url: https://${{ needs.prepare.outputs.app-name }}.${{ needs.prepare.outputs.environment }}.example.com
    needs:
      - prepare
      - build-app
      - build-migrations
    env:
      DOCKER_TAG: ${{ needs.build-app.outputs.docker_tags }}
      DOCKER_DIGEST: ${{ needs.build-app.outputs.docker_digest }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          bash scripts/deploy.sh
