name: Deployment

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      environment:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.app-name }}-${{ inputs.environment }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ inputs.environment }}
      app-name: ${{ inputs.app-name }}
    steps:
      - uses: actions/checkout@v3

  build-app:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      packages: write
    outputs:
      docker-tags: ${{ steps.build.outputs.tags }}
      docker-digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: build
        uses: ./.github/actions/docker-build
        with:
          app-name: ${{ needs.prepare.outputs.app-name }}
          docker-target: production
          environment: ${{ needs.prepare.outputs.environment }}

  build-migrations:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      packages: write
    outputs:
      docker-tags: ${{ steps.build.outputs.tags }}
      docker-digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: build
        uses: ./.github/actions/docker-build
        with:
          app-name: ${{ needs.prepare.outputs.app-name }}
          docker-target: migrations
          environment: ${{ needs.prepare.outputs.environment }}

  scan:
    runs-on: ubuntu-latest
    needs:
      - prepare
      - build-app
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build-app.outputs.docker-tags }}
          format: "sarif"
          output: "trivy-${{ needs.prepare.outputs.environment }}-scan.sarif"
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-${{ needs.prepare.outputs.environment }}-scan.sarif"

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.prepare.outputs.app-name }}-${{ needs.prepare.outputs.environment }}
      url: https://${{ needs.prepare.outputs.app-name }}.${{ needs.prepare.outputs.environment }}.example.com
    needs:
      - prepare
      - build-app
      - build-migrations
    env:
      DOCKER_TAG: ${{ needs.build-app.outputs.docker-tags }}
      DOCKER_DIGEST: ${{ needs.build-app.outputs.docker-digest }}
      DOCKER_MIGRATIONS_TAG: ${{ needs.build-migrations.outputs.docker-tags }}
      DOCKER_MIGRATIONS_DIGEST: ${{ needs.build-migrations.outputs.docker-digest }}
      K8S_NAMESPACE: ${{ needs.prepare.outputs.app-name }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          bash scripts/deploy.sh
