name: Deployment

on:
  push:

env:
  APP_ENV: "production"
  APP_NAME: "purple"

concurrency:
  group: ${{ github.workflow }}-${{ gitub-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.APP_ENV }}
      app-name: ${{ env.APP_NAME }}
    steps:
      - run: |

  build-app:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      packages: write
    outputs:
      docker_tags: ${{ steps.meta.outputs.tags }}
      docker_digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: ../../actions/docker-build
        with:
          app-name: ${{ needs.prepare.outputs.app-name }}
          app-env: ${{ needs.prepare.outputs.environment }}

  build-migrations:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      packages: write
    outputs:
      docker_tags: ${{ steps.meta.outputs.tags }}
      docker_digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
        id: buildx
      - uses: actions/cache@v2
        id: docker-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ needs.prepare.outputs.app-name }}-${{ needs.prepare.outputs.environment }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ needs.prepare.outputs.app-name }}-${{ needs.prepare.outputs.environment }}-
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: "ghcr.io/crgeary/w-${{ needs.prepare.outputs.app-name }}"
          tags: |
            type=sha,enable=true,prefix=migrations-,format=long
          labels:
            org.opencontainers.image.title=${{ needs.prepare.outputs.app-name }}
            org.opencontainers.image.vendor=CrGeary
      - uses: docker/build-push-action@v4
        id: build
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          target: production
          build-args: |
            APP_NAME=${{ needs.prepare.outputs.app-name }}
          push: true
          file: docker/Dockerfile
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  scan:
    runs-on: ubuntu-latest
    needs:
      - prepare
      - build-app
    permissions:
      security-events: write
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build-app.outputs.docker_tags }}
          format: "sarif"
          output: "trivy-${{ needs.prepare.outputs.environment }}-scan.sarif"
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-${{ needs.prepare.outputs.environment }}-scan.sarif"

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.prepare.outputs.app-name }}-${{ needs.prepare.outputs.environment }}
      url: https://${{ needs.prepare.outputs.app-name }}.${{ needs.prepare.outputs.environment }}.example.com
    needs:
      - prepare
      - build-app
      - build-migrations
    env:
      DOCKER_TAG: ${{ needs.build-app.outputs.docker_tags }}
      DOCKER_DIGEST: ${{ needs.build-app.outputs.docker_digest }}
      DOCKER_MIGRATIONS_TAG: ${{ needs.build-migrations.outputs.docker_tags }}
      DOCKER_MIGRATIONS_DIGEST: ${{ needs.build-migrations.outputs.docker_digest }}
      K8S_NAMESPACE: ${{ needs.prepare.outputs.app-name }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          bash scripts/deploy.sh
