name: GIT

on:
  pull_request:

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.pull_request.base }}
          echo "----"
          echo ${{ github.pull_request.head }}