name: GIT

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - closed
      - reopened
      - synchronize

jobs:
  diff:
    if: contains(github.event.pull_request.labels.*.name, 'preview')
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.diff.outputs.apps }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: diff
        run: |
          echo "apps=$(git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} -- apps/ | sed -E 's/apps\/([a-z0-9\-]+)\/.*$/\1/g' | awk '!seen[$0]++' | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: diff
    strategy:
      matrix:
        app-name: ${{ fromJson(needs.diff.outputs.apps) }}
    steps:
      - run: echo ${{ matrix.app-name }}
