name: GIT

on:
  pull_request:

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ toJson(github.pull_request.base) }}
          echo "----"
          echo ${{ toJson(github.pull_request.head) }}