name: GIT

on:
  pull_request:

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          echo ${{ github.event.pull_request.base.sha }}
          echo ${{ github.event.pull_request.head.sha }}

          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}

          git diff --dirstat=files,0 ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} applications/ | sed -E 's/^[ 0-9.]+% //g' | sed -E 's/applications\/([a-z0-9\-]+)\/.*$/\1/g' | awk '!seen[$0]++'