name: GIT

on:
  pull_request:

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          apps=$(git diff \
            --dirstat=files,0 \
            ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} \
            -- apps/ \
            | sed -E 's/^[ 0-9.]+% //g' \
            | sed -E 's/apps\/([a-z0-9\-]+)\/.*$/\1/g' \
            | awk '!seen[$0]++')
          
          echo $apps
        