name: GIT

on:
  pull_request:

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.diff.outputs.apps }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: diff
        run: |
          apps=$(git diff \
            --dirstat=files,0 \
            ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} \
            -- apps/ \
            | sed -E 's/^[ 0-9.]+% //g' \
            | sed -E 's/apps\/([a-z0-9\-]+)\/.*$/\1/g' \
            | awk '!seen[$0]++')
          
          echo "apps=$apps" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: diff
    strategy:
      matrix:
        app-name: needs.diff.outputs.apps
    steps:
      - run: echo ${{ matrix.app-name }}
      