name: GIT

on:
  pull_request:

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.pull_request.sha }}
          echo ${{ github.event.pull_request.sha }}