name: GIT

on:
  pull_request:

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.pull_request.base.sha }}
          echo ${{ github.event.pull_request.head.sha }}

          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}