name: GIT

on:
  pull_request:

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.pull_request.base.sha }}
          echo ${{ github.event.pull_request.target.sha }}

          echo ${{ toJson(github.event.pull_request) }}