name: Main

on:
  push:
    paths:
      - .github/workflows/**

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo ::set-output name=output1::${{ toJSON(['hello', 'world']) }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      matrix:
        app-name: ${{ fromJson(needs.job1.outputs.output1) }}
    steps:
      - run: echo "${{ matrix.value }}"
