name: Main

on:
  push:
    paths:
      - .github/workflows/**

jobs:
  get_affected_apps:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.sets-matrix-output.outputs.value }}
    steps:
      - id: sets-matrix-output
        name: Set matrix output
        run: |
          echo "value=redemption" >> $GITHUB_OUTPUT

  deploy:
    uses: crgeary/test-workflows/.github/workflows/deployment.yaml@main
    with:
      app-name: ${{ needs.get_affected_apps.outputs.matrix }}
