name: Main

on:
  push:
    paths:
      - .github/workflows/**

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"

  deploy:
    uses: crgeary/test-workflows/.github/workflows/deployment.yaml@main
    with:
      app-name: ${{ needs.job1.outputs.output1 }}
