name: Push

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      app-names: ${{ steps.calculate.outputs.app-names }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: calculate
        run: |
          echo "app-names=$(git diff --name-only ${{ github.event.before }}...${{ github.event.after }} -- apps/ | sed -E 's/apps\/([a-z0-9\-]+)\/.*$/\1/g' | awk '!seen[$0]++' | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT

  start:
    needs:
      - diff
    uses: ./.github/workflows/deployment.yaml
    secrets: inherit
    strategy:
      matrix:
        app-name: ${{ fromJson(needs.diff.outputs.app-names) }}
    with:
      app-name: ${{ matrix.app-name }}
      app-environment: "production"
