name: Deployment

on:
  push:

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-name: ["blue", "green", "purple"]
    steps:
      - uses: ./.github/workflows/deployment.yaml
        with:
          app-name: ${{ matrix.app-name }}
          environment: "staging"
    permissions:
      packages: write
      security-events: write
