name: Deployment

on:
  push:

jobs:
  prepare:
    uses: ./.github/workflows/deployment.yaml
    with:
      app-name: "purple"
      environment: "staging"
    permissions:
      packages: write
      security-events: write
