name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.diff.outputs.apps }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: diff
        run: |
          echo "apps=$(git diff --name-only ${{ github.event.before }}...${{ github.event.after }} -- apps/ | sed -E 's/apps\/([a-z0-9\-]+)\/.*$/\1/g' | awk '!seen[$0]++' | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT

  deploy:
    needs:
      - diff
    strategy:
      matrix:
        app-name: ${{ fromJson(needs.diff.outputs.apps) }}
    uses: ./.github/workflows/deployment.yaml
    with:
      app-name: ${{ matrix.app-name }}
      environment: "staging"
    permissions:
      packages: write
      security-events: write
